# This is a basic workflow to help you get started with Actions

name: Latest blog post workflow
on:
  schedule:
    - cron: 50 1/6 * * *
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: TiG000/TiG000@main
        with:
          max_post_count: 10
          feed_list: "https://shenxianpeng.github.io/atom.xml"
