# This is a basic workflow to help you get started with Actions

name: Latest blog post workflow
on:
  schedule:
    - cron: "0 */6 * * 4-7"

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruanyf/weekly@master
        with:
          max_post_count: 10
          feed_list: "https://www.ruanyifeng.com/"
